# Generated by Django 5.2.6 on 2025-11-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataeasy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cliente_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
