# Generated by Django 5.2.8 on 2025-11-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataeasy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='tipo_movimiento',
            field=models.CharField(default='salida', max_length=50),
        ),
    ]
