# Generated by Django 5.2.6 on 2025-11-13 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataeasy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguridadUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta1', models.CharField(blank=True, max_length=255)),
                ('respuesta1', models.CharField(blank=True, max_length=255)),
                ('pregunta2', models.CharField(blank=True, max_length=255)),
                ('respuesta2', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seguridad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguridad de Usuario',
                'verbose_name_plural': 'Seguridad de Usuarios',
            },
        ),
    ]
